#!/usr/bin/env bash

cd "$WALG_ENVDIR"

echo $DRYCC_MINIO_ACCESSKEY > AWS_ACCESS_KEY_ID
echo $DRYCC_MINIO_SECRETKEY > AWS_SECRET_ACCESS_KEY
echo "s3://$DRYCC_MINIO_BUCKET/$PG_MAJOR" > WALE_S3_PREFIX
echo "${DRYCC_MINIO_ENDPOINT}" > AWS_ENDPOINT
if [ "${DRYCC_MINIO_LOOKUP}" == "path" ]; then
  echo "true" > AWS_S3_FORCE_PATH_STYLE
fi
echo $DRYCC_MINIO_BUCKET > BUCKET_NAME
