#!/usr/bin/env bash

cd "$WALG_ENVDIR"

echo $DRYCC_STORAGE_ACCESSKEY > AWS_ACCESS_KEY_ID
echo $DRYCC_STORAGE_SECRETKEY > AWS_SECRET_ACCESS_KEY
echo "s3://$DRYCC_STORAGE_BUCKET/$PG_MAJOR" > WALE_S3_PREFIX
echo "${DRYCC_STORAGE_ENDPOINT}" > AWS_ENDPOINT
if [ "${DRYCC_STORAGE_LOOKUP}" == "path" ]; then
  echo "true" > AWS_S3_FORCE_PATH_STYLE
fi
echo $DRYCC_STORAGE_BUCKET > BUCKET_NAME
