apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: drycc-database
spec:
  podSelector:
    matchLabels:
      app: drycc-database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}