apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drycc-database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drycc-database
subjects:
- kind: ServiceAccount
  name: drycc-database
