apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-database
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: drycc-database
  selector:
    matchLabels:
      app: drycc-database
      cluster-name: drycc-database
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9187"
        prometheus.io/scrape: "true"
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: drycc-database
        cluster-name: drycc-database
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset.type "component" "" "extraMatchLabels" .Values.podAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset.type "component" "" "extraMatchLabels" .Values.podAntiAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values ) | nindent 10 }}
      serviceAccountName: drycc-database
      containers:
      - name: drycc-database
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/database:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 10 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        {{- include "database.envs" . | indent 8 }}
        {{- with index .Values "resources" }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if not .Values.diagnosticMode.enabled }}
        lifecycle:
          preStop:
            exec:
              command:
                - /usr/bin/env
                - bash
                - -c
                - |
                  # switch leader pod if the current pod is the leader
                  if curl --fail http://localhost:8008/read-write; then
                    init-stack patronictl switchover --force
                  fi
        livenessProbe:
          failureThreshold: 3                            
          httpGet:       
            path: /liveness
            port: 8008
            scheme: HTTP   
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - init-stack
              - pg_isready
              - -q
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        {{- end }}
        volumeMounts:
        - name: database-data
          mountPath: /data
      - name: drycc-database-metrics
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/database:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 10 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 10 }}
        {{- else }}
        command:
        - init-stack
        args:
        - postgres_exporter
        {{- end }}
        ports:
        - containerPort: 9187
          protocol: TCP
        env:
        - name: DATA_SOURCE_URI
          value: "127.0.0.1:5432/postgres?sslmode=disable"
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: user
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: password
        startupProbe:
          initialDelaySeconds: 10
          tcpSocket:
              port: 9187
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 15
          successThreshold: 1
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /
            port: 9187
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /
            port: 9187
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: database-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
  {{- else }}
      volumes:
      - name: database-data
        emptyDir: {}
  {{- end }}
