apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  labels:
    app: drycc-database
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
data: {{ if eq .Values.global.database_location "on-cluster"}}
  user: {{ if .Values.username | default "" | ne "" }}{{ .Values.username | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  password: {{ if .Values.password | default "" | ne "" }}{{ .Values.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}{{ else if eq .Values.global.database_location "off-cluster"}}
  url: {{ .Values.postgres.url | b64enc }}{{ end }}
