apiVersion: v1
kind: Service
metadata:
  name: drycc-database-replica
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
    app: drycc-database
    role: replica
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: drycc-database
    role: replica
