{{ if eq .Values.global.databaseLocation "on-cluster"}}
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  labels:
    app: drycc-database
    heritage: drycc
data:
  superuser: {{ include "common.secrets.lookup" (dict "secret" "database-creds" "key" "superuser" "defaultValue" (.Values.superuser | default (randAlpha 32) | lower) "context" $) }}
  superuser-password: {{ include "common.secrets.lookup" (dict "secret" "database-creds" "key" "superuser-password" "defaultValue" (.Values.superuserPassword | default (randAlphaNum 32)) "context" $) }}
  replicator: {{ include "common.secrets.lookup" (dict "secret" "database-creds" "key" "replicator" "defaultValue" (.Values.replicator | default (randAlpha 32) | lower) "context" $) }}
  replicator-password: {{ include "common.secrets.lookup" (dict "secret" "database-creds" "key" "replicator-password" "defaultValue" (.Values.replicatorPassword | default (randAlphaNum 32) | lower) "context" $) }}
  user: {{ include "common.secrets.lookup" (dict "secret" "database-creds" "key" "user" "defaultValue" (.Values.user | default (randAlpha 32) | lower) "context" $) }}
  password: {{ include "common.secrets.lookup" (dict "secret" "database-creds" "key" "password" "defaultValue" (.Values.password | default (randAlphaNum 32)) "context" $) }}
{{- end }}
